Repository AzureAD/microsoft-authentication-library-for-go, pull requests merged in 2021-04, with the labels that each got.

#204 survey added to README.md
  README.md
Labels: documentation

#205 Bugfix - Use refresh token when access token is expired
  apps/internal/base/internal/storage/storage.go
Labels: bug

#206 Adding ability to pass signed assertion
  apps/confidential/confidential.go
  apps/confidential/confidential_test.go
  apps/internal/oauth/oauth.go
  apps/internal/oauth/ops/accesstokens/accesstokens.go
Labels: enhancement
