Repository AzureAD/microsoft-authentication-library-for-go, pull requests merged in 2021-06, with the labels that each got.

#217 Compare scopes case insensitive
  apps/internal/oauth/ops/accesstokens/accesstokens_test.go
  apps/internal/oauth/ops/accesstokens/tokens.go
Labels: enhancement

#215 Adding removeAccount()
  apps/confidential/confidential.go
  apps/internal/base/base.go
  apps/internal/base/internal/storage/storage.go
  apps/internal/base/internal/storage/storage_test.go
  apps/internal/oauth/ops/authority/authority.go
  apps/public/public.go
  apps/tests/integration/integration_test.go
Labels: fundamentals

#223 Removing use of log package
  apps/internal/oauth/ops/wstrust/defs/wstrust_mex_document.go
Labels: bug

#228 Modifying confidential client secret sample to use the latest API
  apps/tests/devapps/client_secret_sample.go
  apps/tests/devapps/main.go
Labels: sample

#229 Fixing typo
  apps/tests/integration/integration_test.go
Labels: documentation

#230 Fixing typo to test new Sonar cloud analysis settings
  apps/confidential/confidential.go
Labels: documentation

#231 MSAL Go 0.3.0
  .github/workflows/golangci-lint.yml
  apps/confidential/confidential.go
  apps/confidential/examples_test.go
  apps/internal/base/base.go
  apps/internal/base/internal/storage/storage.go
  apps/internal/base/internal/storage/storage_test.go
  apps/internal/oauth/ops/accesstokens/accesstokens.go
  apps/internal/oauth/ops/accesstokens/accesstokens_test.go
  apps/internal/oauth/ops/accesstokens/tokens.go
  apps/internal/oauth/ops/authority/authority.go
  apps/internal/oauth/ops/wstrust/defs/wstrust_mex_document.go
  apps/internal/version/version.go
  apps/public/public.go
  apps/tests/devapps/client_certificate_sample.go
  apps/tests/devapps/client_secret_sample.go
  apps/tests/devapps/confidential_config.json
  apps/tests/devapps/main.go
  apps/tests/devapps/sample_utils.go
  apps/tests/integration/integration_test.go
Labels: enhancement

#235 Use a period at the end of README
  README.md
Labels: documentation
