Repository AzureAD/microsoft-authentication-library-for-go, pull requests merged in 2021-03, with the labels that each got.

#186 Only trigger CI/CD when a PR is labelled
  .github/workflows/go.yml
  .github/workflows/golangci-lint.yml
Labels: bug

#187 Use http://localhost for interactive flow
  apps/internal/local/server.go
  apps/internal/local/server_test.go
Labels: enhancement

#188 Make redirect URI a required parameter for auth code flow
  apps/confidential/confidential.go
  apps/confidential/confidential_test.go
  apps/internal/base/base.go
  apps/public/public.go
Labels: bug

#189 Updating config files for samples
  apps/tests/devapps/README.md
  apps/tests/devapps/confidential_config.json
  apps/tests/devapps/config.json
Labels: sample

#191 Fixing lint errors in the dev branch build
  apps/internal/base/base.go
  apps/tests/devapps/main.go
Labels: fundamentals

#184 Exposing suggestedCacheKey in the cache interface for custom token cache
  apps/cache/cache.go
  apps/confidential/confidential.go
  apps/confidential/confidential_test.go
  apps/internal/base/base.go
  apps/internal/base/internal/storage/storage.go
  apps/internal/base/internal/storage/storage_test.go
  apps/internal/oauth/ops/accesstokens/tokens.go
  apps/internal/oauth/ops/authority/authority.go
  apps/public/public.go
  apps/tests/devapps/sample_cache_accessor.go
Labels: enhancement, fundamentals

#192 Adding support for SubjectName/Issuer (SNI) authentication
  apps/confidential/confidential.go
  apps/internal/base/base.go
  apps/internal/oauth/ops/accesstokens/accesstokens.go
  apps/internal/oauth/ops/authority/authority.go
Labels: enhancement

#194 fixing lint errors
  apps/confidential/confidential.go
Labels: fundamentals

#197 Fixing JSON marshal bug on empty map values
  apps/internal/base/internal/storage/items.go
  apps/internal/base/internal/storage/items_test.go
  apps/internal/json/marshal.go
  apps/internal/json/marshal_test.go
Labels: bug

#199 Trying to fix formatting
  apps/internal/base/internal/storage/items_test.go
Labels: fixed

#200 Fixing typo
  apps/cache/cache.go
Labels: fixed

#201 Adding version file
  apps/internal/oauth/ops/internal/comm/comm.go
  apps/internal/version/version.go
Labels: enhancement
