Repository AzureAD/microsoft-authentication-library-for-go, pull requests merged in 2022-05, with the labels that each got.

#315 Upgrade minimum Go version to 1.17
  .github/workflows/go.yml
  go.mod
Labels: fundamentals

#317 Fix incompatible test code
  apps/confidential/confidential_test.go
  apps/internal/oauth/ops/accesstokens/accesstokens_test.go
Labels: test

#316 Release 0.5.1
  apps/confidential/confidential_test.go
  apps/internal/oauth/oauth.go
  apps/internal/oauth/ops/accesstokens/accesstokens.go
  apps/internal/oauth/ops/accesstokens/accesstokens_test.go
  apps/internal/version/version.go
  apps/testdata/test-cert.pem
Labels: in progress

#318 Merge Release 0.5.1 back to dev branch
  apps/confidential/confidential_test.go
  apps/internal/oauth/ops/accesstokens/accesstokens_test.go
  apps/internal/version/version.go
Labels: in progress
