Repository AzureAD/microsoft-authentication-library-for-go, pull requests merged in 2023-04, with the labels that each got.

#402 Prevent persistent cache data races
  apps/internal/base/base.go
  apps/internal/base/base_test.go
  apps/internal/base/internal/storage/storage.go
  apps/internal/base/internal/storage/storage_test.go
Labels: bug

#408 Remove r.login.microsoftonline.com
  README.md
  apps/internal/oauth/ops/authority/authority.go
  apps/internal/oauth/ops/authority/authority_test.go
Labels: enhancement

#410 Update broken tests
  apps/internal/base/base_test.go
  apps/internal/oauth/oauth_test.go
Labels: bug

#412 MSAL Go 1.0.0
  README.md
  apps/internal/base/base.go
  apps/internal/base/base_test.go
  apps/internal/base/internal/storage/storage.go
  apps/internal/base/internal/storage/storage_test.go
  apps/internal/oauth/oauth.go
  apps/internal/oauth/oauth_test.go
  apps/internal/oauth/ops/authority/authority.go
  apps/internal/oauth/ops/authority/authority_test.go
  apps/internal/version/version.go
Labels: test
