Repository AzureAD/microsoft-authentication-library-for-go, pull requests merged in 2023-02, with the labels that each got.

#383 Delete vestigial option function types
  apps/confidential/confidential.go
  apps/internal/version/version.go
  apps/public/public.go
Labels: GA

#384 Rename public client CreateAuthCodeURL -> AuthCodeURL
  apps/public/public.go
  apps/public/public_test.go
  apps/tests/devapps/authorization_code_sample.go
  apps/tests/devapps/confidential_auth_code_sample.go
Labels: GA

#386 Rename confidential.WithAccessor to WithCache
  apps/confidential/confidential.go
  apps/confidential/confidential_test.go
  apps/public/public.go
  apps/tests/devapps/client_certificate_sample.go
  apps/tests/devapps/client_secret_sample.go
Labels: GA

#387 Upgrade dependencies
  go.mod
  go.sum
Labels: GA

#389 Remove unused confidential client UserID
  apps/confidential/confidential.go
Labels: GA

#391 Replace NewCredFromCert with NewCredFromCertChain
  apps/confidential/confidential.go
  apps/confidential/confidential_test.go
  apps/confidential/examples_test.go
  apps/tests/devapps/client_certificate_sample.go
Labels: GA

#390 Remove unnecessary options structs
  apps/confidential/confidential.go
  apps/public/public.go
Labels: GA

#392 Upgrade CI tools
  .github/workflows/go.yml
  .github/workflows/golangci-lint.yml
  apps/internal/oauth/oauth.go
Labels: fundamentals, GA

#378 Adding ExportReplace to support the Context object [breaking change for 1.0]
  apps/cache/cache.go
  apps/confidential/confidential.go
  apps/confidential/confidential_test.go
  apps/internal/base/base.go
  apps/internal/base/base_test.go
  apps/public/public.go
  apps/public/public_test.go
  apps/tests/devapps/confidential_auth_code_sample.go
  apps/tests/devapps/device_code_flow_sample.go
  apps/tests/devapps/main.go
  apps/tests/devapps/sample_cache_accessor.go
  apps/tests/devapps/username_password_sample.go
  apps/tests/integration/integration_test.go
Labels: enhancement, GA
